version: '3'
services:
  zookeeper:
    image: registry.cn-shenzhen.aliyuncs.com/xiyan-blog/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"  
    restart: always
    networks:
      - xiyan
  kafka:
    image: registry.cn-shenzhen.aliyuncs.com/xiyan-blog/kafka
    container_name: kafka
    restart: always
    networks:
      - xiyan
    volumes: 
        - /etc/localtime:/etc/localtime
    ports:
      - "9092:9092"
    environment:
<<<<<<< HEAD
      KAFKA_ADVERTISED_HOST_NAME: kafka   ## 宿主机IP
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181      
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${IP}:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LOG_RETENTION_HOURS: 120
      KAFKA_MESSAGE_MAX_BYTES: 10000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10000000
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 60000
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DELETE_RETENTION_MS: 1000  
=======
      - KAFKA_ADVERTISED_HOST_NAME: kafka   ## 宿主机IP
      - KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181      
      - KAFKA_ADVERTISED_PORT: 9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${IP}:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_LOG_RETENTION_HOURS=120
      - KAFKA_MESSAGE_MAX_BYTES=10000000
      - KAFKA_REPLICA_FETCH_MAX_BYTES=10000000
      - KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS=60000
      - KAFKA_NUM_PARTITIONS=3
      - KAFKA_DELETE_RETENTION_MS=1000  
>>>>>>> 88a8be76a4b1e7503755ba34e221671e21459370
      
networks:
  xiyan:
    external: true