version: '3'
services:
  nginx:
    image: registry.cn-shenzhen.aliyuncs.com/xiyan-blog/nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80  
      - 8600:8600
    networks:
      - xiyan
    volumes:
      - ../data/nginx_data/:/home/aisys/xiyan_data/
      - ../config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../config/nginx/xiyan.conf:/etc/nginx/conf.d/default.conf
networks:
  xiyan:
    external: true
